### ISSUE TITLE
Is Tarantool 2 supported?

### ISSUE THREAD

**Issue by snaffi** [tarantool/go-tarantool#70] opened 2018-11-18 16:36 UTC

**Comment by Totktonada** [comment] 2018-11-19 01:19
@funny-falcon The protocol is described [here][1]. One can use tarantool-c connector [code][2] as example.

[1]: https://tarantool.io/en/doc/2.1/dev_guide/internals/sql_protocol/
[2]: https://github.com/tarantool/tarantool-c/blob/master/tnt/tnt_execute.c

**Comment by funny-falcon** [comment] 2018-11-19 04:55
Ok, will do that soon.

**Comment by Totktonada** [comment] 2021-11-14 00:46
Looks as duplicate of #62. I would close this issue.

**Comment by Totktonada** [comment] 2021-12-13 05:56
Closing as duplicate of #62.

**Closed by Totktonada** 2021-12-13 05:56 UTC
