### ISSUE TITLE
How to pass map/object/table for 2nd argument?

### ISSUE THREAD

**Issue by kokizzu** [tarantool/go-tarantool#100] opened 2021-06-25 14:17 UTC
tried this:

```
a.Call(`box.schema.space.create`, []interface{}{
		`test1`,
		struct{
			Engine string `msgpack:"engine"`
			IfNotExists bool `msgpack:"if_not_exists"`
		}{
			Engine:      Vinyl,
			IfNotExists: true,
		},
	})

a.Call(`box.schema.space.create`,  []interface{}{
		`test1`,
		map[string]interface{}{`if_not_exists`:true, `engine`:`vinyl`},
	})
```

both didn't work, it shows error `unsupported Lua type 'function' (0x20)`, without parameter it works tho

if I change `if_not_exists` to type string, it shows proper error tho: `Illegal parameters, options parameter 'if_not_exists' should be of type boolean (0x1)`

passing empty `map[string]interface{}` works, passing empty struct also works.

**EDIT**: apparently the function calls works normally, it just that have deserialization error, updating to latest `msgpack.v5` have no effect

**Comment by Totktonada** [comment] 2021-11-09 20:45
Duplicate of #94?

Create a wrapper function for `box.schema.space.create`, where you'll discard a return value.

**Comment by Totktonada** [comment] 2021-12-13 05:30
Closed as duplicate. Feel free to reopen if you have more to say on the topic.

**Closed by Totktonada** 2021-12-13 05:30 UTC
