### ISSUE TITLE
Update link to "Connectors" chapter in README

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/go-tarantool#109] opened 2021-11-08 14:35 UTC
AFAIU the link must point to https://www.tarantool.io/en/doc/latest/getting_started/getting_started_go/

**Comment by AnaNek** [comment] 2022-04-10 16:05
I suppose it is closed by f297cfed2a03b0842c89947cc781204760782a1c

**Comment by Totktonada** [comment] 2022-04-10 17:54
Seems so. Thanks!

Duplicate of #130, closed in PR #131.

**Closed by Totktonada** 2022-04-10 17:54 UTC
Labels: teamE, 1sp, code health
